#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : {{ cookiecutter.project_name }}
author                      : {{ cookiecutter.project_author }}
copyright                   : "{% now 'local', '%Y' %}"
logo                        : logo.png


###############################################################################
# Execution settings
# See https://jupyterbook.org/content/execute.html
execute:
    execute_notebooks: 'off'
  #  exclude_patterns:
  #      - 'pattern1'


###############################################################################
# LaTeX-specific settings
latex:
    latex_engine: "pdflatex"
    latex_documents:
        targetname: "book.tex"
    use_jupyterbook_latex: true
    biblio-style: "author_year"


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib


# Information about where the book exists on the web
repository:
  url: https://github.com/{{ cookiecutter.project_author }}/{{ cookiecutter.project_slug }}  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)


# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true


###############################################################################
# HTML-specific settings
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  # use_repository_button: true
  # use_issues_button: true
  # use_edit_page_button: true
  html_show_sourcelink: false
  #extra_navbar: '<hr> Powered by <a href="https://jupyterbook.org">Jupyter Book</a> '
  #extra_footer: ''
  comments:
    hypothesis: false
  # utterances: false


###############################################################################
# Parse and render settings
# See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
parse:
    myst_enable_extensions:
        - amsmath
        - attrs_inline
        - colon_fence
        - deflist
        - dollarmath
        - fieldlist
        - html_admonition
        - html_image
        - linkify
        - replacements
        - smartquotes
        - substitution
        - tasklist
    myst_url_schemes: [mailto, http, https]


###############################################################################
# Options to configure the Sphinx document engine
sphinx:
  # recursive_update: true
  local_extensions:
    _sphinx_config: .
  extra_extensions:
  - 'nbsphinx'
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.intersphinx'
  - 'sphinx.ext.autodoc.typehints'
  - 'sphinx_autodoc_typehints'  # <-- ?
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.viewcode'   # Needs to be put BEFORE autoapi.extension!
  - 'autoapi.extension'
  - 'sphinx.ext.coverage'
  - 'sphinx.ext.autosectionlabel'
  - 'sphinx.ext.napoleon'
  - 'sphinx_autodoc_defaultargs'
  - 'sphinx.ext.doctest'
  - 'sphinxcontrib.images'
  # - 'sphinx_toolbox.collapse'
  # - 'sphinx_toolbox.decorators'
  config:
    napoleon_use_param: True
    napoleon_preprocess_types: False
    napoleon_attr_annotations: True
    # napoleon_use_admonition_for_examples: False
    napoleon_use_admonition_for_notes: True
    # napoleon_use_admonition_for_references: False
    # always_document_param_types: False
    # typehints_defaults: braces
    autodoc_typehints: description
    autodoc_typehints_format: short
    autoapi_dirs: ['../src/']
    autoapi_python_class_content: both
    autoapi_keep_files: false
    autoapi_root: '_autoapi'
    # autoapi_ignore: []
    autoapi_options: [members, 
                      undoc-members, 
                      # private-members, 
                      imported-members, 
                      inherited-members, 
                      # show-module-summary, 
                      # show-inheritance, 
                      # show-inheritance-diagram
                      ]
    autoapi_member_order: groupwise
    intersphinx_mapping:
      xmip: ['https://cmip6-preprocessing.readthedocs.io/en/latest/', 'https://cmip6-preprocessing.readthedocs.io/en/latest/objects.inv']
      sphinx: ['https://www.sphinx-doc.org/en/master/', 'https://www.sphinx-doc.org/en/master/objects.inv']
      python: ['https://docs.python.org/3.12/', 'https://docs.python.org/3.12/objects.inv']
      matplotlib: ['https://matplotlib.org/stable/', 'https://matplotlib.org/stable/objects.inv']
      cartopy: ['https://scitools.org.uk/cartopy/docs/latest/', 'https://scitools.org.uk/cartopy/docs/latest/objects.inv']
      numpy: ['https://numpy.org/doc/stable/', 'https://numpy.org/doc/stable/objects.inv']
      sklearn: ['https://scikit-learn.org/stable/', 'https://scikit-learn.org/stable/objects.inv']
      pandas: ['https://pandas.pydata.org/pandas-docs/stable/', 'https://pandas.pydata.org/pandas-docs/stable/objects.inv']
      scipy: ['https://docs.scipy.org/doc/scipy/', 'https://docs.scipy.org/doc/scipy/objects.inv']
      xarray: ['https://docs.xarray.dev/en/stable/', 'https://docs.xarray.dev/en/stable/objects.inv']
    nb_custom_formats:
      .md:
         - jupytext.reads
         - fmt: myst
    images_config: 
      backend: 'LightBox2'
    html_theme: furo   # furo, sphinx_rtd_theme, pydata_sphinx_theme, sphinx_book_theme, furo, sphinx_material, sphinx_immaterial
    pygments_style: sphinx
    bibtex_reference_style: author_year

html_use_opensearch: 'https://docs.python.org/3.12/'
