#!/usr/bin/env python3
"""Bootstrap a `.copier-answers.yml` for a project generated by the old
cookiecutter/cruft-based version of this template, so `copier update` works
on it going forward.

Reads the project's `.cruft.json` (written by cruft, or by `cruft link` for
plain-cookiecutter projects), maps its cookiecutter keys onto the copier
template's current question keys, and writes `.copier-answers.yml`. It does
not touch any other file in the project.

Usage:
    uv run scripts/migrate_cookiecutter_to_copier.py <project-dir>
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

import yaml

TEMPLATE_REPO = "https://github.com/markusritschel/cookiecutter-pyproject"
SRC_PATH = "gh:markusritschel/cookiecutter-pyproject"

# Old cookiecutter.json key -> current copier.yml question key (MYL-43).
RENAMED_KEYS = {
    "project_author": "user_name",
    "email": "user_email",
    "github_username": "github_user",
}


def load_cruft_context(cruft_json: Path) -> dict:
    data = json.loads(cruft_json.read_text())
    try:
        context = data["context"]["cookiecutter"]
    except KeyError as exc:
        raise SystemExit(
            f"{cruft_json}: missing 'context.cookiecutter' — not a cruft/cookiecutter answers file"
        ) from exc
    # Drop cookiecutter-internal bookkeeping keys (_template, _commit, _copy_without_render, ...).
    return {k: v for k, v in context.items() if not k.startswith("_")}


def map_to_copier_answers(context: dict) -> dict:
    return {RENAMED_KEYS.get(k, k): v for k, v in context.items()}


def resolve_template_commit(template_repo: str) -> str:
    try:
        result = subprocess.run(
            ["git", "ls-remote", template_repo, "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        raise SystemExit(
            f"Could not resolve HEAD of {template_repo} ({exc}). Pass --commit explicitly."
        ) from exc
    if not result.stdout.strip():
        raise SystemExit(
            f"`git ls-remote {template_repo} HEAD` returned nothing. Pass --commit explicitly."
        )
    return result.stdout.split()[0]


def build_answers_file(answers: dict, commit: str, src_path: str) -> str:
    ordered = {"_commit": commit, "_src_path": src_path, **answers}
    header = "# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY\n"
    return header + yaml.safe_dump(
        ordered, sort_keys=False, default_flow_style=False, allow_unicode=True
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "project_dir",
        type=Path,
        nargs="?",
        default=Path("."),
        help="Path to the existing cookiecutter-generated project (default: current directory)",
    )
    parser.add_argument(
        "--cruft-json",
        type=Path,
        default=None,
        help="Path to the project's .cruft.json (default: <project-dir>/.cruft.json)",
    )
    parser.add_argument(
        "--template-repo",
        default=TEMPLATE_REPO,
        help="URL of the copier template repo, used to resolve --commit's default (default: %(default)s)",
    )
    parser.add_argument(
        "--src-path",
        default=SRC_PATH,
        help="Value to record as _src_path (default: %(default)s)",
    )
    parser.add_argument(
        "--commit",
        default=None,
        help="Git ref/commit to record as _commit. Defaults to the template repo's current HEAD.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Where to write the answers file (default: <project-dir>/.copier-answers.yml)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the answers file instead of writing it",
    )
    args = parser.parse_args()

    project_dir = args.project_dir.resolve()
    cruft_json = args.cruft_json or project_dir / ".cruft.json"
    output = args.output or project_dir / ".copier-answers.yml"

    if not cruft_json.exists():
        raise SystemExit(
            f"{cruft_json} not found. Pass --cruft-json to point at the project's cruft context file."
        )
    if output.exists() and not args.dry_run:
        raise SystemExit(
            f"{output} already exists — remove it first if you want to regenerate it."
        )

    answers = map_to_copier_answers(load_cruft_context(cruft_json))
    commit = args.commit or resolve_template_commit(args.template_repo)
    content = build_answers_file(answers, commit, args.src_path)

    if args.dry_run:
        print(content, end="")
        return

    output.write_text(content)
    print(f"Wrote {output}")
    print(f"Recorded template commit: {commit}")
    print("Next: cd into the project and run `copier update --trust` to verify.")


if __name__ == "__main__":
    main()
