# See https://docs.astral.sh/uv/guides/integration/pre-commit/
# may require 'uvx pre-commit install' to be run to have an effect
repos:
  # Manages uv lockfile and exports dependencies to requirements format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.2 
    hooks:
      - id: uv-lock
      - id: uv-export

  # Lints and auto-fixes code style issues, then formats code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
