# See https://docs.astral.sh/uv/guides/integration/pre-commit/
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.6
    hooks:
      # Update the uv lockfile whenever there are changes made to pyproject.toml
      - id: uv-lock
      - id: uv-export
