name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - click
  - colorama
  - dask
  - Deprecated
  - docopt
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter-book
  - jupyterbook-latex
  - jupyterlab
  - jupyternotify
  - jupytext
  - markdown
  - matplotlib
  - mystmd
  - nodejs
  - numpy
  - pandas
  - pytest
  - python-dotenv
  - ruff
  - tqdm
  - xarray
  - pip
