name: {{ cookiecutter.project_slug }}
dependencies:
  - python=3.9
  - python-dotenv
  - ipython
  - jupyterlab
  - ipywidgets
  - nodejs
  - nb_conda_kernels
  - ipykernel
  - seaborn
  - tqdm
  - matplotlib
  - numpy
  - scipy
  - pandas
  - xarray
  - scikit-learn
  - netcdf4
  - pytest
  - docopt
  - click
  - jupyter-book
  - jupytext
  - jupyternotify
  - markdown
  - sphinx
  - sphinxcontrib-apidoc
  - sphinxcontrib-mermaid
  - nbsphinx
  - sphinx-issues
  - sphinx-book-theme
  - pydata-sphinx-theme
  - sphinx-rtd-theme
  - myst-parser
  - sphinx-issues
  - sphinxcontrib-bibtex
  - sphinxcontrib-apidoc
  - sphinx-autodoc-typehints
  - sphinx-toolbox
  - pip
  - pip:
    - jupyterbook-latex
    - sphinxcontrib-napoleon2
    - rinohtype
    - sphinx-autodoc-defaultargs
