name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
<<<<<<< HEAD
  - python=3.9
  - python-dotenv
  - ipython
  - jupyterlab
  - ipywidgets
  - nodejs
  - nb_conda_kernels
  - ipykernel
  - seaborn
  - tqdm
  - matplotlib
  - numpy
  - scipy
  - pandas
  - xarray
  - scikit-learn
  - netcdf4
  - pytest
  - docopt
=======
>>>>>>> 3eb01c5 (Update requirements)
  - click
  - colorama
  - Deprecated
  - docopt
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter-book
  - jupyterbook-latex
  - jupyterlab
  - jupyternotify
  - jupytext
  - markdown
  - matplotlib
  - mystmd
  - nodejs
  - numpy
  - pandas
  - pytest
  - python-dotenv
  - tqdm
  - xarray
  - pip
