name: CI/CD Workflow

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build: 

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install CookieCutter & run setup
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter wheel
        pip install colorama
        cookiecutter . --no-input

    - name: Install dependencies
      working-directory: ./scientific-project-python-boilerplate
      run: pip install -r requirements.txt
      
    - name: Run tests
      working-directory: ./scientific-project-python-boilerplate
      run: |
        python -m pytest


    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
